server:
  port: 56020

spring:
  application:
    name: quickstart-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 518e02a6-d1a1-4227-81e7-590a0043fa40

logging:
  level:
    root: info
    org.springframework: info